import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_excel("Business Data Sample.xlsx")
pd.set_option('display.float_format','{:.2f}'.format)


#total revenue
df['Revenue'] = df['quantity'] * df['amount']
revenue_by_category = df.groupby('Category')['Revenue'].agg(['max'])

revenue_by_brand = df.groupby('brand')['Revenue'].agg(['max'])
print("Total Revenue by Category is \n\n",revenue_by_category ,"\nTotal Revenue by Brand is \n\n",revenue_by_brand)


#top 5 customers contributing most revenue
revenue_by_customer = df.groupby('customer_name')['Revenue'].sum().reset_index()
top_5_customer = revenue_by_customer.sort_values('Revenue',ascending = False).head(5)
print("\ntop 5 customers contributing most revenue\n\n",top_5_customer)


# most frequently sold product by UPC for each customer type
product_sold = df.groupby(['date','customer_type'])['upc (Unit per Case)'].sum().reset_index()
frequent_sold_product = product_sold.sort_values('date',ascending = False)
print("\nmost frequently sold product by UPC for each customer type\n\n",frequent_sold_product)


#city wise transaction(amount) trend
transac = df.groupby('City')['amount'].sum().reset_index()
print("\ncity wise transaction(amount) trend\n\n",transac)

x = transac['City']
y = transac['amount']


plt.xlabel('City')
plt.ylabel('Scale')
plt.title('City-Wise Transaction')

plt.plot(x,y,marker = '.',label = 'Amount')
for i, j in enumerate(y):
    plt.text(x[i], j, f'₹ {j:.2f}', ha='center', va='bottom')

plt.legend()
plt.show()


#total revenue generated by city
rev_generated = df.groupby('City')['Revenue'].sum().reset_index()
print("\ntotal revenue generated by city\n\n",rev_generated)


#number of transactions per city
num_of_transaction_per_city = df['City'].value_counts()
print("\nnumber of transactions per city\n\n",num_of_transaction_per_city)

#average quantity sold per transaction for each channel description
avg_qty_sold_per_transac = df.groupby(['channel_description','amount'])['quantity'].sum().reset_index()
print("\naverage quantity sold per transaction for each channel description\n\n",avg_qty_sold_per_transac[['channel_description','quantity']])

#top reason for transaction and their impact on revenue
reason = df.groupby('reason for transaction')['Revenue'].agg('max',).reset_index()
top_reason = reason.sort_values(by='Revenue',ascending=False)
print('top reason for transaction and their impact on revenue\n\n',top_reason)


#pivot table -> city-wise revenue and quantity trends
city_revenue = df.groupby('City')['Revenue'].sum().reset_index()
city_qty = df.groupby('City')['quantity'].sum().reset_index()
pivot_df = pd.merge(city_revenue,city_qty,on = 'City')
pivot_df.set_index(['City'],inplace = True)


table = df.pivot_table(
    values=['Revenue', 'quantity'],  
    index='City',                    
    aggfunc='sum'                    
)
print("pivot table -> city-wise revenue and quantity trends\n\n",table)

 
df.to_excel('Business Data Sample.xlsx')





